# 1
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P, REST_REVIEW R
WHERE P.MEMBER_ID = R.MEMBER_ID
AND P.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
                  GROUP BY MEMBER_ID
                  ORDER BY COUNT(*) DESC
                  LIMIT 1)
ORDER BY R.REVIEW_DATE, REVIEW_TEXT

#2
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
                 GROUP BY MEMBER_ID
                 ORDER BY COUNT(*) DESC
                 LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT
