# 1 - 한 개의 테이블로 합치기 -> union all
SELECT FLAVOR
FROM (SELECT *
     FROM FIRST_HALF
     UNION ALL
     SELECT *
     FROM JULY) AS A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;

# 2
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY (SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)) DESC
LIMIT 3
