SELECT CAR.CAR_ID, CAR.CAR_TYPE,
FLOOR(CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR, 
CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
WHERE CAR.CAR_ID = HISTORY.CAR_ID
AND CAR.CAR_TYPE = PLAN.CAR_TYPE
AND CAR.CAR_TYPE IN ('세단', 'SUV')
AND CAR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE END_DATE > '2022-11-01')
AND PLAN.DURATION_TYPE = '30일 이상'
AND (CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100 * 30) >= 500000
AND (CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100 * 30) < 2000000
GROUP BY CAR.CAR_ID
ORDER BY FEE DESC, PLAN.CAR_TYPE, CAR.CAR_ID DESC
