SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(INFO.USER_ID)) USERS
FROM USER_INFO INFO, ONLINE_SALE SALE
WHERE GENDER IS NOT NULL AND SALE.USER_ID = INFO.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER
