SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
AND SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
