SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_USER USERS
ON BOARD.WRITER_ID = USERS.USER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
